import { appendAuditLog } from "@/lib/audit-store";
import { documentSequences, pdfTemplateCatalog } from "@/lib/document-catalog";
import { createDemoRecord, readDemoRecordsSnapshot, writeDemoRecordsSnapshot } from "@/lib/demo-store";
import type { PdfTemplate } from "@/lib/pdf/generator";

type Row = Record<string, string>;

export function issueDocumentNumber(documentType: string) {
  const prefix = documentSequences.find(([type]) => type === documentType)?.[1] || "DOC";
  const key = `medtech-demo:doc-sequence:${prefix}:${new Date().getFullYear()}`;
  const next = typeof window === "undefined" ? 1 : Number(localStorage.getItem(key) || "1");
  if (typeof window !== "undefined") localStorage.setItem(key, String(next + 1));
  return `${prefix}-${new Date().getFullYear()}-${String(next).padStart(4, "0")}`;
}

export function documentTypeFor(moduleKey: string, tab: string, record: Row) {
  if (moduleKey === "sales") return tab === "Quotations" ? "Quotation" : tab === "Orders" ? "Sales Order" : tab.includes("Lead") ? "Lead" : tab.includes("Enquiry") ? "Enquiry" : tab.includes("Opportunities") ? "Opportunity" : tab.includes("Commissions") ? "Commission Run" : "Lead";
  if (moduleKey === "finance") return tab === "Payments" ? "Payment" : tab.includes("Credit") ? "Invoice" : "Invoice";
  if (moduleKey === "procurement") return tab === "RFQs" ? "RFQ" : tab === "Purchase Requests" ? "Purchase Request" : tab === "Goods Receipts" ? "GRN" : "Purchase Order";
  if (moduleKey === "shipping") return tab === "Packing Lists" ? "Packing List" : tab === "Shipments" ? "Shipment" : tab === "Proof of Delivery" ? "Proof of Delivery" : tab === "Customs / Clearance Documents" ? "Clearance Packet" : "Delivery Note";
  if (moduleKey === "service") return tab === "AMC Contracts" ? "AMC Contract" : tab === "Service Reports" ? "Service Report" : "Service Ticket";
  if (moduleKey === "projects") return tab === "Milestones" || tab === "Milestone Billing" ? "Milestone" : "Project";
  if (moduleKey === "hr") return tab === "Leave" ? "Leave Request" : tab === "Payroll" ? "Payroll Run" : record["Settlement No"] ? "EOS Case" : "Employee Letter";
  if (moduleKey === "approvals") return "Approval Request";
  return "Management Report";
}

export function templateForDocumentType(documentType: string): PdfTemplate {
  return pdfTemplateCatalog.find(item => item.document === documentType)?.template || "report";
}

export function finalDocumentError(record: Row) {
  const status = `${record["Approval Status"] || record.Status || ""}`.toLowerCase();
  if (status && /draft|pending|submitted|review|rejected|cancelled/.test(status) && !/approved|confirmed|sent|generated|paid|final|closed/.test(status)) return "Approval is required before generating a final document.";
  return "";
}

export function recordGeneratedDocument(input: { document: string; sourceModule: string; sourceRecord: string; documentNumber: string; generatedBy: string }) {
  const row = { Document: input.document, "Source module": input.sourceModule, "Source record": input.sourceRecord, "Document number": input.documentNumber, "Generated by": input.generatedBy, "Generated at": new Date().toLocaleString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }), Status: "Generated", Action: "Download / Preview" };
  const key = "documents:Generated Documents";
  writeDemoRecordsSnapshot(key, [createDemoRecord(row), ...readDemoRecordsSnapshot(key, [])]);
  appendAuditLog({ action: "PDF", module: "Documents", record: input.documentNumber, details: `${input.document} generated from ${input.sourceModule} ${input.sourceRecord}` });
  return row;
}

export function validateEmail(value: string) {
  return !value || /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}

export function validatePhone(value: string) {
  return !value || /^\+?[0-9 ()-]{6,20}$/.test(value);
}

export function validateDateOrder(start: string, end: string) {
  const from = new Date(start); const to = new Date(end);
  return !start || !end || Number.isNaN(from.getTime()) || Number.isNaN(to.getTime()) || from <= to;
}

export function validateAmountCurrency(value: string) {
  return /^[A-Z]{3}\s?-?\d[\d,]*(\.\d{1,2})?$/.test(value.trim());
}
