"use client";

import type { RecordFieldSuggestion, RecordFieldType } from "@/components/record-modal";
import { createDemoRecord, readDemoRecordsSnapshot, writeDemoRecordsSnapshot, type DemoRecord } from "@/lib/demo-store";
import { medtechScopeViews } from "@/lib/medtech-scope-data";
import { productMasterRows, supplierMasterRows, type MasterDataConfig } from "@/lib/master-data";
import { approvalRequired, hasApprovedApproval, money } from "@/lib/approval-matrix";

type Row = Record<string, string>;

export type ProcurementAction = "generate-rfq" | "compare-supplier" | "generate-po" | "generate-grn" | "generate-vendor-bill" | "generate-po-documents";

export const procurementColumns: Record<string, string[]> = {
  "Purchase Requests": ["PR No", "Requesting Module", "Requested By", "Business Unit", "Department", "Product Lines", "Required Date", "Justification", "Status"],
  RFQs: ["RFQ No", "Supplier", "Currency", "Expected Lead Time", "Quote Validity", "Product Lines", "Quoted Cost", "Status"],
  "Supplier Comparison": ["Comparison No", "RFQ No", "Supplier", "Price", "Currency", "Lead Time", "Payment Terms", "Availability", "Notes", "Winning Supplier", "Status"],
  "Purchase Orders": ["PO No", "Supplier", "Currency", "Product Lines", "Total", "Approval Status", "Delivery ETA", "Status"],
  "Goods Receipts": ["GRN No", "PO No", "Supplier", "Received Lines", "Warehouse", "Location", "Lot/Serial/Batch", "Expiry Date", "QC Status", "Status"],
  "Vendor Bills": ["Vendor Bill No", "PO No", "GRN No", "Supplier", "Currency", "Amount", "Bill Date", "Due Date", "Accounting Posting", "Status"],
  "PO Documents": ["Document No", "PO No", "Supplier", "Document Type", "Generated By", "Generated At", "Status"]
};

const prefixes: Record<string, string> = {
  "Purchase Requests": "PR-2026-",
  RFQs: "RFQ-2026-",
  "Supplier Comparison": "CMP-2026-",
  "Purchase Orders": "PO-2026-",
  "Goods Receipts": "GRN-2026-",
  "Vendor Bills": "BILL-DRAFT-2026-",
  "PO Documents": "PO-DOC-2026-"
};

const firstColumn: Record<string, string> = Object.fromEntries(Object.entries(procurementColumns).map(([tab, columns]) => [tab, columns[0]]));
const businessUnits = ["Medical Equipment", "Diagnostics", "Pharma", "Lab", "Service", "Projects"];
const departments = ["Procurement", "Warehouse", "Sales", "Service", "Projects", "Finance"];
const statuses = ["Draft", "Submitted", "Pending approval", "Approved", "Rejected", "Cancelled", "Completed"];

export function getProcurementConfig(tab: string): MasterDataConfig | null {
  const columns = procurementColumns[tab];
  if (!columns) return null;
  return {
    keyColumn: firstColumn[tab],
    filterColumns: columns.filter(column => ["Business Unit", "Department", "Supplier", "Currency", "Approval Status", "QC Status", "Status"].includes(column)),
    searchColumns: columns,
    selectOptions: selectOptionsFor(tab),
    fieldTypes: fieldTypesFor(columns),
    defaultValues: defaultsFor(tab),
    suggestions: procurementSuggestions(),
    prepareSave: (input, records, selected) => prepareRow(tab, input, records, selected),
    validateImportRow: (input, rowNumber, records, seen) => prepareRow(tab, input, records, null, rowNumber, seen)
  };
}

export function procurementActionsFor(tab: string) {
  if (tab === "Purchase Requests") return [{ action: "generate-rfq" as const, label: "Generate RFQ" }];
  if (tab === "RFQs") return [{ action: "compare-supplier" as const, label: "Add comparison" }];
  if (tab === "Supplier Comparison") return [{ action: "generate-po" as const, label: "Generate PO draft" }];
  if (tab === "Purchase Orders") return [{ action: "generate-grn" as const, label: "Generate GRN" }, { action: "generate-po-documents" as const, label: "PO PDF" }];
  if (tab === "Goods Receipts") return [{ action: "generate-vendor-bill" as const, label: "Generate vendor bill" }];
  return [];
}

export function runProcurementAction(action: ProcurementAction, records: DemoRecord[], currentUser: string) {
  if (!records.length) return { error: "Select at least one record first." };
  if (action === "generate-rfq") return writeTarget("RFQs", records.map((record, index) => rfqFromPr(record, index)), "RFQ No", records.map(() => ({ Status: "RFQ Created" })), "RFQ draft generated locally");
  if (action === "compare-supplier") return writeTarget("Supplier Comparison", records.map((record, index) => comparisonFromRfq(record, index)), "Comparison No", records.map(() => ({ Status: "Under comparison" })), "Supplier comparison created locally");
  if (action === "generate-po") return writeTarget("Purchase Orders", records.map((record, index) => poFromComparison(record, index)), "PO No", records.map(() => ({ Status: "PO Drafted" })), "PO draft generated locally");
  if (action === "generate-po-documents") return writeTarget("PO Documents", records.map((record, index) => poDocument(record, currentUser, index)), "PO No", undefined, "PO document logged locally");
  if (action === "generate-grn") {
    const blocked = records.find(record => poApprovalError(record, currentUser));
    if (blocked) return { error: poApprovalError(blocked, currentUser) };
    return writeTarget("Goods Receipts", records.map((record, index) => grnFromPo(record, index)), "GRN No", records.map(() => ({ Status: "Finalized", "Approval Status": "Approved" })), "GRN generated locally");
  }
  const bills = records.map((record, index) => vendorBillFromGrn(record, index));
  writeFinanceBills(bills);
  writeInventoryReceipts(records);
  return writeTarget("Vendor Bills", bills, "Vendor Bill No", records.map((record, index) => ({ Status: "Completed", "Vendor Bill No": bills[index]["Vendor Bill No"] })), "Vendor bill draft, finance draft, and inventory receipt created locally");
}

function prepareRow(tab: string, input: Record<string, unknown>, records: DemoRecord[], selected?: DemoRecord | null, rowNumber = 0, seen = new Set<string>()) {
  const columns = procurementColumns[tab];
  const row = Object.fromEntries(columns.map(column => [column, String(input[column] ?? defaultsFor(tab)[column] ?? "").trim()])) as Row;
  const key = firstColumn[tab];
  if (!row[key] || row[key] === "Auto generated") row[key] = nextId(tab, records);
  const required = tab === "Supplier Comparison" ? [key, "RFQ No", "Supplier", "Price"] : columns.filter(column => !["Justification", "Notes", "Expiry Date", "Accounting Posting"].includes(column));
  const missing = required.filter(field => !row[field]);
  if (missing.length) throw new Error(prefix(rowNumber) + `Missing ${missing.join(", ")}`);
  const duplicate = records.find(record => record[key]?.toLowerCase() === row[key].toLowerCase() && record.__id !== selected?.__id);
  if (seen.has(row[key].toLowerCase()) || duplicate) throw new Error(prefix(rowNumber) + `${key} already exists`);
  seen.add(row[key].toLowerCase());
  return row;
}

function writeTarget(tab: string, rows: Row[], uniqueField: string, sourceUpdates: Row[] | undefined, message: string) {
  const seed = medtechScopeViews[`procurement.${tab}`]?.rows ?? [];
  const existing = readDemoRecordsSnapshot(`procurement:${tab}`, seed);
  const incomingKeys = new Set(rows.map(row => row[uniqueField]).filter(Boolean));
  writeDemoRecordsSnapshot(`procurement:${tab}`, [...rows.map(createDemoRecord), ...existing.filter(row => !incomingKeys.has(row[uniqueField]))]);
  return { targetTab: tab, sourceUpdates, message: `${rows.length} ${message}` };
}

function rfqFromPr(pr: Row, index: number) {
  const product = productFor(pr["Product Lines"]);
  const supplier = supplierFor(product?.["Supplier Name"]);
  const supplierName = supplier?.["Principal / Supplier Name"] ?? product?.["Supplier Name"] ?? supplierMasterRows[0]["Principal / Supplier Name"];
  const currency = supplier?.Currency ?? product?.["Cost Currency"] ?? "QAR";
  return {
    "RFQ No": nextTargetId("RFQs", index + 1),
    Supplier: supplierName,
    Currency: currency,
    "Expected Lead Time": `${product?.["Lead Time Days"] ?? supplier?.["Lead Time Days"] ?? "14"} days`,
    "Quote Validity": dateOffset(14),
    "Product Lines": pr["Product Lines"],
    "Quoted Cost": amount(product?.["QAR Cost"] ?? "0", currency),
    Status: "Draft",
    "PR No": pr["PR No"],
    "Payment Terms": supplier?.["Payment Terms"] ?? "30 days"
  };
}

function comparisonFromRfq(rfq: Row, index: number) {
  const supplier = supplierFor(rfq.Supplier);
  return {
    "Comparison No": nextTargetId("Supplier Comparison", index + 1),
    "RFQ No": rfq["RFQ No"],
    Supplier: rfq.Supplier,
    Price: rfq["Quoted Cost"],
    Currency: rfq.Currency,
    "Lead Time": rfq["Expected Lead Time"],
    "Payment Terms": supplier?.["Payment Terms"] ?? rfq["Payment Terms"] ?? "30 days",
    Availability: "Available",
    Notes: "Local demo comparison - no supplier email/API sent",
    "Winning Supplier": rfq.Supplier,
    Status: "Submitted",
    "Product Lines": rfq["Product Lines"]
  };
}

function poFromComparison(comparison: Row, index: number) {
  const total = comparison.Price || "QAR 0";
  return {
    "PO No": nextTargetId("Purchase Orders", index + 1),
    Supplier: comparison["Winning Supplier"] || comparison.Supplier,
    Currency: comparison.Currency || "QAR",
    "Product Lines": comparison["Product Lines"] || "Procurement lines",
    Total: total,
    "Approval Status": money(total) > 50000 ? "Approval required" : "Not required",
    "Delivery ETA": dateOffset(days(comparison["Lead Time"]) || 14),
    Status: "Draft",
    "Business Unit": productFor(comparison["Product Lines"])?.["Business Unit"] ?? "Procurement"
  };
}

function grnFromPo(po: Row, index: number) {
  const product = productFor(po["Product Lines"]);
  return {
    "GRN No": nextTargetId("Goods Receipts", index + 1),
    "PO No": po["PO No"],
    Supplier: po.Supplier,
    "Received Lines": po["Product Lines"],
    Warehouse: "Main Warehouse",
    Location: product?.["Cold Chain Required"] === "Yes" ? "Cold Store" : "Receiving Bay",
    "Lot/Serial/Batch": product?.["Batch Tracking Required"] === "Yes" ? `LOT-${Date.now().toString().slice(-6)}` : "N/A",
    "Expiry Date": product?.["Expiry Controlled"] === "Yes" ? dateOffset(365) : "",
    "QC Status": "Pending",
    Status: "Draft",
    Currency: po.Currency,
    Total: po.Total
  };
}

function vendorBillFromGrn(grn: Row, index: number) {
  return {
    "Vendor Bill No": nextTargetId("Vendor Bills", index + 1),
    "PO No": grn["PO No"],
    "GRN No": grn["GRN No"],
    Supplier: grn.Supplier,
    Currency: grn.Currency || "QAR",
    Amount: grn.Total || "QAR 0",
    "Bill Date": today(),
    "Due Date": dateOffset(30),
    "Accounting Posting": "Not posted - local draft only",
    Status: "Draft"
  };
}

function poDocument(po: Row, currentUser: string, index: number) {
  return {
    "Document No": nextTargetId("PO Documents", index + 1),
    "PO No": po["PO No"],
    Supplier: po.Supplier,
    "Document Type": "Purchase Order PDF",
    "Generated By": currentUser,
    "Generated At": new Date().toLocaleString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }),
    Status: "Generated"
  };
}

function poApprovalError(po: Row, requestedBy: string) {
  const source = { sourceModule: "Procurement", sourceRecord: po["PO No"], requestType: "Purchase order", requestedBy, amount: money(po.Total), businessUnit: po["Business Unit"] || "Procurement" };
  return approvalRequired(source).required && !hasApprovedApproval("Procurement", po["PO No"], "Purchase order") ? `${po["PO No"]} needs approved purchase order approval before GRN.` : "";
}

function writeFinanceBills(bills: Row[]) {
  const key = "finance:Vendor Bills";
  const seed = medtechScopeViews["finance.Vendor Bills"]?.rows ?? [];
  const existing = readDemoRecordsSnapshot(key, seed);
  const docs = new Set(bills.map(bill => bill["Vendor Bill No"]));
  writeDemoRecordsSnapshot(key, [...bills.map(bill => createDemoRecord({ "Bill No": bill["Vendor Bill No"], "Source Module": "Procurement GRN", Supplier: bill.Supplier, Currency: bill.Currency, Lines: `${bill["PO No"]} / ${bill["GRN No"]}`, Subtotal: bill.Amount, Tax: "QAR 0", Total: bill.Amount, "Due Date": bill["Due Date"], Status: "Draft" })), ...existing.filter(row => !docs.has(row["Bill No"]))]);
}

function writeInventoryReceipts(grns: Row[]) {
  const movementSeed = medtechScopeViews["inventory.Stock Movements"]?.rows ?? [];
  const stockSeed = medtechScopeViews["inventory.Stock On Hand"]?.rows ?? [];
  const movements = readDemoRecordsSnapshot("inventory:Stock Movements", movementSeed);
  const stock = readDemoRecordsSnapshot("inventory:Stock On Hand", stockSeed);
  const nextStock = [...stock];
  const newMovements = grns.map(grn => {
    const product = productName(grn["Received Lines"]);
    const master = productFor(grn["Received Lines"]);
    const qty = quantity(grn["Received Lines"]);
    const existing = nextStock.find(row => row.Product === product && row.Location === grn.Location && row["Lot/Batch/Serial"] === grn["Lot/Serial/Batch"]);
    if (existing) {
      existing["Quantity On Hand"] = addQty(existing["Quantity On Hand"], qty);
      existing["Available Quantity"] = addQty(existing["Available Quantity"], qty);
    } else {
      nextStock.unshift(createDemoRecord({ Product: product, SKU: master?.["SKU Code"] ?? "", Warehouse: grn.Warehouse || "Main Warehouse", Location: grn.Location, "Lot/Batch/Serial": grn["Lot/Serial/Batch"], "Expiry Date": grn["Expiry Date"] || "", "Quantity On Hand": String(qty), "Reserved Quantity": "0", "Available Quantity": String(qty), "Min Stock": master?.["Min Stock"] ?? "0", "Max Stock": master?.["Max Stock"] ?? "0", "QC Status": grn["QC Status"] === "Pending" ? "Quarantine" : "Released", "Cold Chain Required": master?.["Cold Chain Required"] ?? "No", Status: grn["QC Status"] === "Pending" ? "Quarantine" : "Available" }));
    }
    return createDemoRecord({ "Movement No": `MOV-2026-${String(Date.now() % 100000).padStart(5, "0")}`, Type: "Procurement GRN receipt", Product: product, SKU: master?.["SKU Code"] ?? "", From: "Supplier", To: grn.Location || grn.Warehouse, "Lot/Batch/Serial": grn["Lot/Serial/Batch"], Quantity: String(qty), Source: grn["GRN No"], Status: "Posted" });
  });
  writeDemoRecordsSnapshot("inventory:Stock Movements", [...newMovements, ...movements].slice(0, 250));
  writeDemoRecordsSnapshot("inventory:Stock On Hand", nextStock.slice(0, 250));
}

function procurementSuggestions(): Record<string, RecordFieldSuggestion[]> {
  const products = productMasterRows.map(product => ({
    value: product["Product Name"],
    label: product["SKU Code"],
    fill: { "Product Lines": product["Product Name"], "Business Unit": product["Business Unit"], Supplier: product["Supplier Name"], Currency: product["Cost Currency"], "Expected Lead Time": `${product["Lead Time Days"]} days`, "Quoted Cost": amount(product["QAR Cost"], product["Cost Currency"]) }
  }));
  const suppliers = supplierMasterRows.map(supplier => ({
    value: supplier["Principal / Supplier Name"],
    label: supplier["Supplier Code"],
    fill: { Supplier: supplier["Principal / Supplier Name"], Currency: supplier.Currency, "Expected Lead Time": `${supplier["Lead Time Days"]} days`, "Payment Terms": supplier["Payment Terms"] }
  }));
  return { "Product Lines": products, "Received Lines": products, Supplier: suppliers, "Winning Supplier": suppliers };
}

function selectOptionsFor(tab: string) {
  return {
    "Requesting Module": ["Sales", "Service", "Projects", "Inventory", "Warehouse"],
    "Business Unit": businessUnits,
    Department: departments,
    Currency: ["QAR", "USD", "EUR", "GBP"],
    "Approval Status": ["Not required", "Approval required", "Pending approval", "Approved", "Rejected"],
    Availability: ["Available", "Partial", "Backorder"],
    Warehouse: ["Main Warehouse", "Cold Store", "Service Stock", "Transit"],
    Location: ["Receiving Bay", "Quality Inspection", "Cold Store", "Main Warehouse"],
    "QC Status": ["Pending", "Released", "Rejected", "Quarantine"],
    Status: statuses,
    ...(tab === "Vendor Bills" ? { "Accounting Posting": ["Not posted - local draft only"] } : {})
  };
}

function fieldTypesFor(columns: string[]) {
  return Object.fromEntries(columns.filter(column => column.includes("Date") || column.includes("ETA") || column.includes("Validity")).map(column => [column, "date" as RecordFieldType]));
}

function defaultsFor(tab: string) {
  const key = firstColumn[tab];
  return { [key]: "Auto generated", Status: "Draft", Currency: "QAR", "Requested By": "M. Said", Department: "Procurement", "Required Date": dateOffset(7), "Quote Validity": dateOffset(14), "Delivery ETA": dateOffset(14), "Bill Date": today(), "Due Date": dateOffset(30), "Approval Status": "Not required", "Accounting Posting": "Not posted - local draft only" };
}

function nextId(tab: string, records: Row[], offset = 1) {
  const column = firstColumn[tab];
  const prefixValue = prefixes[tab];
  const max = records.map(record => Number(String(record[column] ?? "").replace(prefixValue, "").replace(/\D/g, ""))).filter(Number.isFinite).reduce((highest, value) => Math.max(highest, value), 0);
  return `${prefixValue}${String(max + offset).padStart(tab === "Purchase Orders" ? 4 : 5, "0")}`;
}

function nextTargetId(tab: string, offset = 1) {
  const seed = medtechScopeViews[`procurement.${tab}`]?.rows ?? [];
  return nextId(tab, readDemoRecordsSnapshot(`procurement:${tab}`, seed), offset);
}

function productFor(value = "") {
  const normalized = value.toLowerCase();
  return productMasterRows.find(product => normalized.includes(product["Product Name"].toLowerCase()) || normalized.includes(product["SKU Code"].toLowerCase()));
}

function supplierFor(value = "") {
  const normalized = value.toLowerCase();
  return supplierMasterRows.find(supplier => supplier["Principal / Supplier Name"].toLowerCase() === normalized || supplier["Supplier Code"].toLowerCase() === normalized || supplier["Principal / Supplier Name"].toLowerCase().includes(normalized));
}

function productName(value = "") {
  return productFor(value)?.["Product Name"] ?? (value.split(/\sx\s|\s-\s/)[0] || "Procurement item");
}

function quantity(value = "") {
  const match = value.match(/\b(\d+(?:\.\d+)?)\b/);
  return match ? Number(match[1]) : 1;
}

function days(value = "") {
  const match = value.match(/\d+/);
  return match ? Number(match[0]) : 0;
}

function addQty(current = "0", qty: number) {
  return String((Number(current.replace(/[^0-9.-]/g, "")) || 0) + qty);
}

function amount(value: string, currency = "QAR") {
  return `${currency} ${Math.round(Number(String(value).replace(/,/g, "")) || 0).toLocaleString("en-US")}`;
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

function dateOffset(daysFromNow: number) {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString().slice(0, 10);
}

function prefix(rowNumber: number) {
  return rowNumber ? `Row ${rowNumber}: ` : "";
}
