"use client";

import type { RecordFieldType } from "@/components/record-modal";
import { appendAuditLog } from "@/lib/audit-store";
import { createDemoRecord, readDemoRecordsSnapshot, writeDemoRecordsSnapshot, type DemoRecord } from "@/lib/demo-store";
import { getModule } from "@/lib/erp-data";
import { medtechScopeViews } from "@/lib/medtech-scope-data";
import type { MasterDataConfig } from "@/lib/master-data";
import { seedSalesWorkflows, workflowTotals, type SalesWorkflowRecord } from "@/lib/sales-workflow";

type Row = Record<string, string>;

export type ProjectAction = "generate-from-pso" | "mark-milestone-complete" | "create-inventory-delivery" | "create-document-pack" | "close-project";
export interface ProjectActionButton { action: ProjectAction; label: string; requiresSelection?: boolean; }

export const projectColumns: Record<string, string[]> = {
  Projects: ["Project No", "Customer", "Business Unit", "Project Type", "Manager", "Start Date", "End Date", "Contract Value", "Budget", "Actual Cost", "Margin", "Status"],
  "Project Tasks": ["Task No", "Project No", "Project", "Task", "Owner", "Due Date", "Priority", "Status"],
  Milestones: ["Milestone No", "Project", "Description", "Planned Date", "Completion %", "Billing %", "Billing Type", "Invoice Draft Status", "Approval Status", "Status"],
  "Department Sub-Quotations": ["Department", "Scope", "Estimated Cost", "Selling Price", "Margin", "Submitted By", "Status"],
  Budgets: ["Budget No", "Project No", "Project", "Contract Value", "Budget", "Actual Cost", "Committed", "Remaining", "Margin", "Status"],
  Deliverables: ["Deliverable No", "Project No", "Project", "Product", "SKU", "Quantity", "Inventory Delivery", "Document", "Status"],
  "Milestone Billing": ["Billing", "Milestone No", "Project", "Customer", "Description", "Billing Type", "Billing %", "Amount", "Retention %", "Invoice Draft Status", "Approval Status", "Status"],
  "Retention Tracking": ["Retention No", "Project No", "Project", "Customer", "Invoice", "Retention %", "Retention Amount", "Release Date", "Invoice Draft", "Status"],
  "Project Documents": ["Document No", "Project No", "Project", "Document Type", "Linked Module", "Linked Record", "Generated By", "Status"],
  "Project Closure": ["Closure No", "Project No", "Project", "Deliverables", "Documents", "Retention", "Customer Sign-off", "Finance Close", "Lessons Learned", "Status"]
};

const firstColumn = Object.fromEntries(Object.entries(projectColumns).map(([tab, columns]) => [tab, columns[0]]));
const prefixes: Record<string, string> = {
  Projects: "PRJ-2026-",
  "Project Tasks": "PTK-2026-",
  Milestones: "PMS-2026-",
  Budgets: "PBG-2026-",
  Deliverables: "PDL-2026-",
  "Milestone Billing": "PMB-2026-",
  "Retention Tracking": "RET-2026-",
  "Project Documents": "PDOC-2026-",
  "Project Closure": "PCL-2026-"
};

export function getProjectConfig(tab: string): MasterDataConfig | null {
  const columns = projectColumns[tab];
  if (!columns) return null;
  return {
    keyColumn: firstColumn[tab],
    filterColumns: columns.filter(column => ["Business Unit", "Project Type", "Billing Type", "Approval Status", "Priority", "Status"].includes(column)),
    searchColumns: columns,
    selectOptions: selectOptionsFor(tab),
    fieldTypes: fieldTypesFor(columns),
    defaultValues: defaultsFor(tab),
    suggestions: {},
    prepareSave: (input, records, selected) => prepareRow(tab, input, records, selected),
    validateImportRow: (input, rowNumber, records, seen) => prepareRow(tab, input, records, null, rowNumber, seen)
  };
}

export function projectActionsFor(tab: string): ProjectActionButton[] {
  if (tab === "Projects") return [{ action: "generate-from-pso", label: "Generate from PSO", requiresSelection: false }];
  if (tab === "Milestones") return [{ action: "mark-milestone-complete", label: "Complete milestone" }];
  if (tab === "Deliverables") return [{ action: "create-inventory-delivery", label: "Inventory delivery" }, { action: "create-document-pack", label: "Document link" }];
  if (tab === "Project Documents") return [{ action: "create-document-pack", label: "Documents link" }];
  if (tab === "Project Closure") return [{ action: "close-project", label: "Close project" }];
  return [];
}

export function runProjectAction(action: ProjectAction, tab: string, records: DemoRecord[], currentUser: string) {
  if (action === "generate-from-pso") {
    const pso = readPsoWorkflows().find(record => record.pathway === "pso" && !projectExistsForPso(record));
    if (!pso) return { error: "No new PSO workflow is ready for local project setup." };
    const created = createProjectFromPso(pso, currentUser);
    return { targetTab: "Projects", upsertKey: "Project No", createdRows: [created.project], message: `${created.project["Project No"]} generated from ${pso.reference}` };
  }
  if (!records.length) return { error: "Select at least one record first." };
  if (action === "mark-milestone-complete") return completeMilestones(records);
  if (action === "create-inventory-delivery") return createInventoryDelivery(records, currentUser);
  if (action === "create-document-pack") return createDocumentLinks(records, currentUser);
  return closeProjects(records);
}

export function createProjectFromPso(record: SalesWorkflowRecord, currentUser: string) {
  const totals = workflowTotals(record);
  const projectNo = record.projectCode && !record.projectCode.includes("HOLD") ? record.projectCode : nextTargetId("Projects");
  const projectName = record.linkedProject || record.title;
  const budget = Math.round(totals.cost * 1.08);
  const project: Row = prepareProject({
    "Project No": projectNo,
    Customer: record.customer,
    "Business Unit": "Projects",
    "Project Type": "Project Sales Order",
    Manager: record.owner,
    "Start Date": today(),
    "End Date": dateOffset(120),
    "Contract Value": qar(totals.net),
    Budget: qar(budget),
    "Actual Cost": "QAR 0",
    Status: "Budget approval"
  });
  writeRows("Projects", [project], "Project No");
  writeRows("Department Sub-Quotations", parseDepartmentQuotes(record.departmentQuotes, currentUser), "Department");
  writeRows("Milestones", milestoneRows(projectName, record.milestoneSchedule), "Milestone No");
  writeRows("Budgets", [budgetRow(projectNo, projectName, project)], "Budget No");
  writeRows("Deliverables", record.lines.map((line, index) => ({
    "Deliverable No": nextTargetId("Deliverables", index + 1),
    "Project No": projectNo,
    Project: projectName,
    Product: line.product,
    SKU: line.sku,
    Quantity: String(line.quantity),
    "Inventory Delivery": "Pending",
    Document: "",
    Status: "Ready for delivery"
  })), "Deliverable No");
  writeRows("Project Documents", [projectDocument(projectNo, projectName, "PSO setup pack", record.reference, currentUser)], "Document No");
  appendAuditLog({ action: "PROJECT SETUP", module: "Projects", record: projectNo, details: `Generated locally from ${record.reference}` });
  return { project, projectName };
}

function completeMilestones(records: DemoRecord[]) {
  const updates = records.map(record => ({ "Completion %": "100", Status: "Completed" }));
  return { sourceUpdates: updates, message: `${records.length} milestone${records.length === 1 ? "" : "s"} marked complete` };
}

function createInventoryDelivery(records: DemoRecord[], currentUser: string) {
  const rows = records.map((record, index) => ({
    "Movement No": `MOV-2026-${String(Date.now() % 100000).padStart(5, "0")}-${index}`,
    Type: "Project delivery dispatch",
    Product: record.Product || "Project deliverable",
    SKU: record.SKU || "",
    From: "Main Warehouse",
    To: "Project Site",
    "Lot/Batch/Serial": record["Project No"] || record.Project,
    Quantity: record.Quantity || "1",
    Source: record["Deliverable No"] || record["Project No"],
    Status: "Posted"
  }));
  writeDemoRecordsSnapshot("inventory:Stock Movements", [...rows.map(createDemoRecord), ...readDemoRecordsSnapshot("inventory:Stock Movements", medtechScopeViews["inventory.Stock Movements"].rows)].slice(0, 250));
  appendAuditLog({ action: "PROJECT DELIVERY", module: "Inventory", record: rows.map(row => row.Source).join(", "), details: `Project delivery posted locally by ${currentUser}` });
  return { targetModule: "inventory", targetTab: "Stock Movements", sourceUpdates: records.map((_, index) => ({ "Inventory Delivery": rows[index]["Movement No"], Status: "Delivered" })), message: `${rows.length} inventory delivery movement${rows.length === 1 ? "" : "s"} posted locally` };
}

function createDocumentLinks(records: DemoRecord[], currentUser: string) {
  const docs = records.map((record, index) => projectDocument(record["Project No"] || "PRJ-LOCAL", record.Project || record["Document Type"] || "Project", "Project document pack", record["Deliverable No"] || record["Document No"] || record["Project No"], currentUser, index + 1));
  writeRows("Project Documents", docs, "Document No");
  writeDemoRecordsSnapshot("documents:Generated Documents", [
    ...docs.map(doc => createDemoRecord({ Document: doc["Document Type"], "Source module": "Projects", "Source record": doc["Linked Record"], "Document number": doc["Document No"], "Generated by": currentUser, "Generated at": today(), Status: "Generated" })),
    ...readDemoRecordsSnapshot("documents:Generated Documents", medtechScopeViews["documents.Generated Documents"].rows)
  ].slice(0, 250));
  appendAuditLog({ action: "PROJECT DOCUMENTS", module: "Projects", record: docs.map(doc => doc["Document No"]).join(", "), details: "Project documents linked locally" });
  return { targetTab: "Project Documents", upsertKey: "Document No", createdRows: docs, sourceUpdates: records.map((_, index) => ({ Document: docs[index]["Document No"] })), message: `${docs.length} project document link${docs.length === 1 ? "" : "s"} created` };
}

function closeProjects(records: DemoRecord[]) {
  const blocked = records.find(record => [record.Deliverables, record.Documents, record.Retention, record["Customer Sign-off"], record["Finance Close"]].some(value => value && !["Complete", "Closed", "Released", "Signed", "Tracked"].includes(value)));
  if (blocked) return { error: `${blocked.Project} closure checklist is not complete.` };
  return { sourceUpdates: records.map(() => ({ Status: "Closed" })), message: `${records.length} project closure${records.length === 1 ? "" : "s"} completed locally` };
}

function prepareRow(tab: string, input: Record<string, unknown>, records: DemoRecord[], selected?: DemoRecord | null, rowNumber = 0, seen = new Set<string>()) {
  const columns = projectColumns[tab];
  const row = Object.fromEntries(columns.map(column => [column, String(input[column] ?? defaultsFor(tab)[column] ?? "").trim()])) as Row;
  const key = firstColumn[tab];
  if (!row[key] || row[key] === "Auto generated") row[key] = nextId(tab, records);
  if (tab === "Projects") Object.assign(row, prepareProject(row));
  if (tab === "Department Sub-Quotations") row.Margin = margin(row["Selling Price"], row["Estimated Cost"]);
  if (tab === "Budgets") Object.assign(row, budgetCalculated(row));
  if (tab === "Milestones") row.Status = milestoneRisk(row);
  const missing = columns.filter(column => !["Actual Cost", "Committed", "Remaining", "Invoice Draft Status", "Invoice Draft", "Document", "Lessons Learned"].includes(column) && !row[column]);
  if (missing.length) throw new Error(prefix(rowNumber) + `Missing ${missing.join(", ")}`);
  if (seen.has(row[key].toLowerCase()) || records.some(record => record[key]?.toLowerCase() === row[key].toLowerCase() && record.__id !== selected?.__id)) throw new Error(prefix(rowNumber) + `${key} already exists`);
  seen.add(row[key].toLowerCase());
  return row;
}

function prepareProject(row: Row): Row {
  const contract = money(row["Contract Value"]);
  const actual = money(row["Actual Cost"]);
  const budget = money(row.Budget);
  const profit = contract - actual;
  const status = actual > budget && budget > 0 ? "Budget watch" : row.Status || "Planning";
  return { ...row, Margin: `${qar(profit)} / ${contract ? ((profit / contract) * 100).toFixed(1) : "0.0"}%`, Status: status };
}

function budgetCalculated(row: Row): Row {
  const budget = money(row.Budget);
  const actual = money(row["Actual Cost"]);
  const committed = money(row.Committed);
  return { ...row, Remaining: qar(Math.max(0, budget - Math.max(actual, committed))), Margin: margin(row["Contract Value"], row["Actual Cost"]), Status: actual > budget && budget > 0 ? "Over budget" : row.Status || "Within budget" };
}

function parseDepartmentQuotes(value: string, currentUser: string) {
  return value.split(/\r?\n/).map(row => row.trim()).filter(Boolean).map(row => {
    const [department = "Projects", amount = "QAR 0"] = row.split(":").map(part => part.trim());
    return { Department: department, Scope: `${department} project sub-quotation`, "Estimated Cost": qar(money(amount) * 0.82), "Selling Price": amount, Margin: margin(amount, qar(money(amount) * 0.82)), "Submitted By": currentUser, Status: "Submitted" };
  });
}

function milestoneRows(project: string, schedule: string) {
  const parts = schedule.split(",").map(value => value.trim()).filter(Boolean);
  return (parts.length ? parts : ["Advance 20%", "Delivery 50%", "Commissioning 20%", "Retention 10%"]).map((part, index) => {
    const percent = String(money(part) || (index === 0 ? 20 : 10));
    const type = /retention/i.test(part) ? "Retention" : /advance/i.test(part) ? "Advance" : "Progress";
    return { "Milestone No": nextTargetId("Milestones", index + 1), Project: project, Description: part.replace(/\d+%?/, "").trim() || type, "Planned Date": dateOffset(30 * (index + 1)), "Completion %": index === 0 ? "0" : "0", "Billing %": percent, "Billing Type": type, "Invoice Draft Status": "Not drafted", "Approval Status": "Draft", Status: "Planned" };
  });
}

function budgetRow(projectNo: string, project: string, source: Row) {
  return { "Budget No": nextTargetId("Budgets"), "Project No": projectNo, Project: project, "Contract Value": source["Contract Value"], Budget: source.Budget, "Actual Cost": source["Actual Cost"], Committed: "QAR 0", Remaining: source.Budget, Margin: source.Margin, Status: "Pending approval" };
}

function projectDocument(projectNo: string, project: string, type: string, source: string, currentUser: string, offset = 1) {
  return { "Document No": nextTargetId("Project Documents", offset), "Project No": projectNo, Project: project, "Document Type": type, "Linked Module": "Documents", "Linked Record": source || projectNo, "Generated By": currentUser, Status: "Generated" };
}

function readPsoWorkflows() {
  try {
    const stored = localStorage.getItem("medtech-demo:sales-workflows:v1");
    return stored ? JSON.parse(stored) as SalesWorkflowRecord[] : seedSalesWorkflows();
  } catch {
    return seedSalesWorkflows();
  }
}

function projectExistsForPso(record: SalesWorkflowRecord) {
  return readDemoRecordsSnapshot("projects:Projects", projectSeeds("Projects")).some(row => row["Project No"] === record.projectCode || row.Customer === record.customer);
}

function writeRows(tab: string, rows: Row[], key: string) {
  const existing = readDemoRecordsSnapshot(`projects:${tab}`, projectSeeds(tab));
  const keys = new Set(rows.map(row => row[key]).filter(Boolean));
  writeDemoRecordsSnapshot(`projects:${tab}`, [...rows.map(createDemoRecord), ...existing.filter(row => !keys.has(row[key]))].slice(0, 250));
}

function projectSeeds(tab: string) {
  return medtechScopeViews[`projects.${tab}`]?.rows ?? (tab === "Projects" ? getModule("projects").rows : []);
}

function selectOptionsFor(tab: string) {
  return {
    "Business Unit": ["Projects", "Medical Equipment", "Diagnostics", "Service", "Lab"],
    "Project Type": ["Project Sales Order", "Turnkey fit-out", "Reference lab expansion", "ICU modernization", "Equipment installation"],
    Priority: ["Low", "Medium", "High", "Critical"],
    "Billing Type": ["Advance", "Progress", "Retention"],
    "Approval Status": ["Draft", "Pending approval", "Approved", "Rejected"],
    "Invoice Draft Status": ["Not drafted", "Drafted"],
    Status: ["Draft", "Planning", "Budget approval", "On track", "At risk", "Milestone at risk", "Budget watch", "Ready to bill", "Delivered", "Closed"],
    ...(tab === "Project Closure" ? { Deliverables: ["Pending", "Complete"], Documents: ["Pending final pack", "Complete"], Retention: ["Pending", "Tracked", "Released"], "Customer Sign-off": ["Pending", "Signed"], "Finance Close": ["Open", "Closed"] } : {})
  };
}

function fieldTypesFor(columns: string[]) {
  return Object.fromEntries(columns.filter(column => column.includes("Date")).map(column => [column, "date" as RecordFieldType]));
}

function defaultsFor(tab: string) {
  return { [firstColumn[tab]]: "Auto generated", "Business Unit": "Projects", "Project Type": "Project Sales Order", "Start Date": today(), "End Date": dateOffset(90), "Contract Value": "QAR 0", Budget: "QAR 0", "Actual Cost": "QAR 0", "Completion %": "0", "Billing %": "0", "Billing Type": "Progress", "Invoice Draft Status": "Not drafted", "Approval Status": "Draft", "Retention %": "10", Status: "Draft" };
}

function milestoneRisk(row: Row) {
  if (money(row["Completion %"]) < 100 && row["Planned Date"] < today()) return "At risk";
  return row.Status || "Planned";
}

function nextTargetId(tab: string, offset = 1) {
  return nextId(tab, readDemoRecordsSnapshot(`projects:${tab}`, projectSeeds(tab)), offset);
}

function nextId(tab: string, records: Row[], offset = 1) {
  const key = firstColumn[tab];
  const prefixValue = prefixes[tab] ?? `${tab.toUpperCase().replace(/[^A-Z]+/g, "-")}-`;
  const max = records.map(record => Number(String(record[key] ?? "").replace(prefixValue, "").replace(/\D/g, ""))).filter(Number.isFinite).reduce((highest, value) => Math.max(highest, value), 0);
  return `${prefixValue}${String(max + offset).padStart(4, "0")}`;
}

function margin(selling: string, cost: string) {
  const sell = money(selling);
  const gross = sell - money(cost);
  return `${qar(gross)} / ${sell ? ((gross / sell) * 100).toFixed(1) : "0.0"}%`;
}

function money(value = "") {
  const match = String(value).replace(/,/g, "").match(/-?\d+(?:\.\d+)?/);
  return match ? Number(match[0]) : 0;
}

function qar(value: number) {
  return `QAR ${Math.round(value).toLocaleString("en-US")}`;
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

function dateOffset(days: number) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
}

function prefix(rowNumber: number) {
  return rowNumber ? `Row ${rowNumber}: ` : "";
}
