export const defaultWpsColumns = [
  "Employee Code",
  "Employee Name",
  "Bank Name",
  "Account Number / IBAN",
  "QID / Employee ID",
  "Month",
  "Year",
  "Paid Days",
  "Net Salary",
  "Remarks"
] as const;

export interface WpsEmployeeMaster {
  employeeCode: string;
  employeeName: string;
  bankName: string;
  accountNumber: string;
  iban: string;
  qidOrEmployeeId: string;
}

export interface WpsPayrollLine {
  employeeCode: string;
  employeeName: string;
  paidDays: number;
  netSalary: number;
  salaryAmount: number;
  remarks: string;
}

export interface WpsRunContext {
  company: string;
  department: string;
  month: string;
  year: string;
  payrollRunId: string;
  generatedBy: string;
  generatedAt: string;
  wpsFormat: string;
}

export interface WpsValidationError {
  employee: string;
  missingField: string;
}

export function validateWpsExport(lines: WpsPayrollLine[], employees: WpsEmployeeMaster[]) {
  const byCode = new Map(employees.map(employee => [employee.employeeCode, employee]));
  const errors: WpsValidationError[] = [];
  lines.forEach(line => {
    const master = byCode.get(line.employeeCode);
    const employee = line.employeeName || line.employeeCode || "Unknown employee";
    if (!line.employeeCode) errors.push({ employee, missingField: "Employee Code" });
    if (!line.employeeName) errors.push({ employee, missingField: "Employee Name" });
    if (!master?.bankName) errors.push({ employee, missingField: "Bank Name" });
    if (!master?.accountNumber && !master?.iban) errors.push({ employee, missingField: "Account Number / IBAN" });
    if (!master?.qidOrEmployeeId) errors.push({ employee, missingField: "QID / Employee ID" });
    if (line.netSalary < 0) errors.push({ employee, missingField: "Non-negative Net Salary" });
    if (line.paidDays <= 0) errors.push({ employee, missingField: "Paid Days" });
    if (line.salaryAmount <= 0) errors.push({ employee, missingField: "Salary Amount" });
  });
  return errors;
}

export function buildWpsRows(lines: WpsPayrollLine[], employees: WpsEmployeeMaster[], context: WpsRunContext, columns = defaultWpsColumns as readonly string[]) {
  const byCode = new Map(employees.map(employee => [employee.employeeCode, employee]));
  return lines.map(line => {
    const master = byCode.get(line.employeeCode);
    const values: Record<string, unknown> = {
      "Employee Code": line.employeeCode,
      "Employee Name": line.employeeName,
      "Bank Name": master?.bankName ?? "",
      "Account Number / IBAN": master?.iban || master?.accountNumber || "",
      "QID / Employee ID": master?.qidOrEmployeeId || line.employeeCode,
      Month: context.month,
      Year: context.year,
      "Paid Days": line.paidDays,
      "Net Salary": line.netSalary,
      Remarks: line.remarks
    };
    return Object.fromEntries(columns.map(column => [column, values[column] ?? ""]));
  });
}

export function buildWpsSummaryRows(lines: WpsPayrollLine[], context: WpsRunContext, columnNames: readonly string[]) {
  const totalNet = lines.reduce((sum, line) => sum + line.netSalary, 0);
  return [
    { Field: "Company", Value: context.company },
    { Field: "Department", Value: context.department },
    { Field: "Month", Value: context.month },
    { Field: "Year", Value: context.year },
    { Field: "Payroll Run ID", Value: context.payrollRunId },
    { Field: "Generated By", Value: context.generatedBy },
    { Field: "Generated At", Value: context.generatedAt },
    { Field: "WPS Format", Value: context.wpsFormat },
    { Field: "Configured Columns", Value: columnNames.join(", ") },
    { Field: "Employee Count", Value: lines.length },
    { Field: "Total Net Salary", Value: totalNet }
  ];
}

